### ISSUE TITLE
Bash variable drush in hook script is not used

### ISSUE THREAD

**Issue by regilero** [acquia/drs-acsf#5]
Instead the default bahs 'drush' command is used (and resolution depends on path). The `${drush}` variable defined in the script is not used.

I made a PR to fix that and some other minor things:

https://github.com/acquia/drs-acsf/pull/4

**Comment by vishalkhode1** [comment]
Merged and released as part of [1.0.0](https://github.com/acquia/drs-acsf/releases/tag/1.0.0).
